name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-26
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install SwiftFormat and SwiftLint
        run: |
          brew install swiftformat swiftlint

      - name: Linting
        run: swiftlint --fix --format && swiftlint --strict
        continue-on-error: true

      - name: Formatting
        run: swiftformat . && swiftformat . --lint
        continue-on-error: true

      - name: Get Swift version
        run: swift --version

      - name: Build Binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x build.sh
          ./build.sh
        continue-on-error: true

  package:
    runs-on: macos-26
    needs: build
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Build Binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create DMG
        run: |
          create-dmg --volname "manis" --skip-jenkins --no-internet-enable --filesystem APFS --icon "manis.app" 0 0 --hide-extension "manis.app" --app-drop-link 0 0 "manis.dmg" ".build/release/manis.app"

      - name: Upload Binary
        uses: actions/upload-artifact@v6
        with:
          name: manis-binary
          path: .build/release/manis
          if-no-files-found: error

      - name: Upload Bundle
        uses: actions/upload-artifact@v6
        with:
          name: manis-app
          path: .build/release/manis.app
          if-no-files-found: error

      - name: Upload DMG
        uses: actions/upload-artifact@v6
        with:
          name: manis-dmg
          path: manis.dmg
          if-no-files-found: error
